;;auto-complete-modeの読み込み
(require 'auto-complete-config)
(ac-config-default)
(setq ac-delay 0.3)
(setq ac-auto-show-menu 0.5)
(add-to-list 'ac-dictionary-directories (locate-user-emacs-file "dict"))
(setq ac-use-menu-map t)
(setq ac-use-fuzzy nil)
(add-to-list 'ac-modes 'objc-mode)
(delq 'ac-source-yasnippet ac-sources)
