(setq pop-up-windows nil)
(require 'popwin nil t)
(when (require 'popwin nil t)
  (setq anything-samewindow nil)
  (setq display-buffer-function 'popwin:display-buffer)
  (push '("anything" :regexp t :height 20) popwin:special-display-config)
  (push '("*magit-edit-log*" :height 0.5) popwin:special-display-config)
  (push '("magit" :regexp t :height 0.5) popwin:special-display-config)
  (push '(dired-mode :position top :height 20) popwin:special-display-config)
  )
