(setenv "PERL5LIB"
        (concat "/Volumes/shibaVM/home/shiba_yu36/shiba_yu36/lib:"
                "/Volumes/shibaVM/usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib64/perl5/site_perl/5.8.7/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib64/perl5/site_perl/5.8.6/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib64/perl5/site_perl/5.8.5/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib/perl5/site_perl/5.8.8:"
                "/Volumes/shibaVM/usr/lib/perl5/site_perl/5.8.7:"
                "/Volumes/shibaVM/usr/lib/perl5/site_perl/5.8.6:"
                "/Volumes/shibaVM/usr/lib/perl5/site_perl/5.8.5:"
                "/Volumes/shibaVM/usr/lib/perl5/site_perl:"
                "/Volumes/shibaVM/usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib64/perl5/vendor_perl/5.8.7/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib64/perl5/vendor_perl/5.8.6/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib64/perl5/vendor_perl/5.8.5/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib/perl5/vendor_perl/5.8.8:"
                "/Volumes/shibaVM/usr/lib/perl5/vendor_perl/5.8.7:"
                "/Volumes/shibaVM/usr/lib/perl5/vendor_perl/5.8.6:"
                "/Volumes/shibaVM/usr/lib/perl5/vendor_perl/5.8.5:"
                "/Volumes/shibaVM/usr/lib/perl5/vendor_perl:"
                "/Volumes/shibaVM/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi:"
                "/Volumes/shibaVM/usr/lib/perl5/5.8.8:"
                (getenv "PERL5LIB")))